### ISSUE TITLE
Cost delayed by an hour

### ISSUE THREAD

**Issue by DK-MGO** [custom-components/zaptec#103]
Hey,

Thank you for a fine integration, does all I need ;o)

Only thing is that I get the reported cost added to the Energy dashboard with an hours delay. Does anyone have the same issue? Any ideas for a fix?

I monitor my electricity directly from my meter (showing usage at 15-17 hours, which was when I was charging). I have also split out the Zaptec load as it's own entity, and this is shown with an hours delay. - The consequence is that the cost calculation is wrong (based on the wrong hourly cost).

I am running the Zaptec integration v. 0.7.1. 

I am in Denmark and the the timezone in the Zaptec portal is set "(UTC+01:00) Central European Time (Berlin)" - Denmark and Berlin are the same. I cannot change the timezone in the Zaptec portal.

![zaptec](https://github.com/custom-components/zaptec/assets/101643418/8b7160fc-45cc-4b2d-ad49-7d8c89087ca4)

![image](https://github.com/custom-components/zaptec/assets/101643418/4f23c75b-a912-4681-ab6a-fdc61bc16b80)

Thank you!

**Comment by sveinse** [comment]
What Zaptec entities are you graphing here?

**Comment by DK-MGO** [comment]
> What Zaptec entities are you graphing here?

I am using: sensor.car_charger_energy_meter

**Comment by DK-MGO** [comment]
Shown correctly on: https://portal.zaptec.com/chargeHistory

![Screenshot_20240513_142043_Chrome~2](https://github.com/custom-components/zaptec/assets/101643418/a968c2d8-dde8-4447-83d6-bf12517bb85c)

**Comment by DK-MGO** [comment]
Seems there is a way to shift the hour - https://community.home-assistant.io/t/offset-sensor-by-an-hour/548808/6

Unknown for now if this will also change the cost calculation...
