### ISSUE TITLE
Bug: Cable lock binary sensor shows opposite status

### ISSUE THREAD

**Issue by Fredrik81** [custom-components/zaptec#106]
The binary sensor "binary_sensor.XXXXXXXX_permanent_cable_lock" show the opposite status (Off = locked and On = Unlocked):
![image](https://github.com/custom-components/zaptec/assets/21292774/7442aa21-8d49-4880-8c08-a4de9bbdb690)

Complete output from "binary_sensor.XXXXXXX_linkoping_charger":
![image](https://github.com/custom-components/zaptec/assets/21292774/e77c0187-0dbe-4eae-8b89-ddcf6acc76b5)
In the zaptec app it is showing as locked:
![image](https://github.com/custom-components/zaptec/assets/21292774/e2b8417e-546e-4d2f-85b9-141eab951358)

If i understand the intension of the code from "binary_sensor.py" the sensor should show On when locked.
```
    ZapBinarySensorEntityDescription(
        key="permanent_cable_lock",
        translation_key="permanent_cable_lock",
        device_class=BinarySensorDeviceClass.LOCK,  # False=unlocked, True=locked
        entity_category=const.EntityCategory.DIAGNOSTIC,
        icon="mdi:lock",
        cls=ZaptecBinarySensorLock,
```

**Comment by sveinse** [comment]
The comment in the zaptec code is incorrect. This is from `homeassisant/component/binary_sensor/__init__.py`: 

<img width="388" alt="image" src="https://github.com/custom-components/zaptec/assets/13770135/ec3930f8-6bd6-4a60-a2e9-3b4324a6fcc6">

The value shall be `false` to indicate that the cable is locked. Opposite of the value from Zaptec.

**Comment by sveinse** [comment]
From the attribute:

<img width="430" alt="image" src="https://github.com/custom-components/zaptec/assets/13770135/5296dfb2-a15e-4618-917a-399d60f0f56b">

That shows the state:

<img width="254" alt="image" src="https://github.com/custom-components/zaptec/assets/13770135/935b7f81-f398-4943-9368-01fe285bd4a0">

Which corresponds to HA state value on:

<img width="373" alt="image" src="https://github.com/custom-components/zaptec/assets/13770135/3a645e01-7401-4572-a88f-41db65929684">

**Comment by Fredrik81** [comment]
Oh ok. This feels counter intuitive as if you have a lock entity on a dashboard it will show unlocked for the cable. 
Also it doesn't follow zaptec (the source) as zaptec says locked and sensor says unlocked. 

Can this be changed to match zaptec?

**Comment by sveinse** [comment]
The polarity of the switch is a decision made by Home assistant -- that's why its opposite of the zaptec value.

Does the sensor show incorrectly in the UI? In my previous post I showed that the HA sensor value of "on" shows as "Unlocked" in the UI. Your case with the value of "off" should be shown in the UI as "Locked". Doesn't it do that?

**Comment by Fredrik81** [comment]
I stand corrected. Thanks for clarification
