### ISSUE TITLE
Control brightness of status indicator

### ISSUE THREAD

**Issue by c0mplex1** [custom-components/zaptec#112]
Please create the possibility to control the brightness of the charging station status indicator from within the integration, so that you do not necessarily have to set it via the Zaptec portal or app.
Thank you.

**Comment by c0mplex1** [comment]
Too bad it's not possible.
Could have been a nice addition to the integration.

Kind regards,
Frank.

**Comment by sveinse** [comment]
I think I've found a way to do it (albeit not officially). It's located in the same system as cable locking, so I'm tempted to give it a go.
