### ISSUE TITLE
Can't Add To Dashboard: No config found.

### ISSUE THREAD

**Issue by tomekwl** [custom-components/zaptec#113]
I have removed the previous and installed 0.7.1 version. Integration added with no problem. Adding to dashboard, however, gives me "No config found" error. What's missing?

**Comment by sveinse** [comment]
Can you please provide more information about what have gone wrong? To be able to assist, some more information is required.

**Comment by sveinse** [comment]
Closing as no more information has been given. Please reopen the issue if there are any updates to the issue.
