### ISSUE TITLE
Feature request: connection status

### ISSUE THREAD

**Issue by Ghannes** [custom-components/zaptec#114]
Hi, 

I am using the integration and works good! However I miss the functionality to check if my Zaptec is connected to the internet. Yesterday it went offline and I would like to create an automation to check for this, and send a notification to my phone.

thanks,
Hans

**Comment by sveinse** [comment]
The Zaptec integration have three entities named "<Something> Installation", "<Something> Circuit" and "<Something> Charger". They have the state "Connected", "Not connected". They should give the status of the charger. Please check your history to check if they did change state when the charger was offline.

**Comment by Ghannes** [comment]
They all say it is connected sand charging. That’s incorrect since I
removed power due to maintenance

Op za 7 sep 2024 om 09:39 schreef Svein Seldal ***@***.***>

**Comment by sveinse** [comment]
There is a an attribute named "is online" that could be added as a entity in the integration. However, this integration relies on cloud poll so it can only reflect the data that Zaptec cloud provides. It does not communicate directly with the charger.

I have removed the AC power to my Zaptec Go, but I see no change in "is online" value after 15 minutes. Even Zaptec portal is reporting charger to be online. I'll keep the test running to see how long time it takes until the cloud detects that the charger is offline.

@Ghannes Does Online Details show your charger offline for the period which the charger was offline? Go to https://portal.zaptec.com -> Chargers -> Select your charger -> Status -> Online? -> Details

**Comment by sveinse** [comment]
A fix for the issue have been pushed to master. Please install the "master" version and test if this fixes the observed problems. @Ghannes

**Comment by Ghannes** [comment]
Thanks for your efforts!

Op di 22 okt 2024 om 20:55 schreef Svein Seldal ***@***.***>

**Comment by sveinse** [comment]
It seems HACS have removed the option of downloading "master", so I've created a beta/pre-release "0.7.2b1" available for download and test.
