### ISSUE TITLE
Is it possible to fetch specific languages?

### ISSUE THREAD

**Issue by sunedall** [custom-components/zaptec#117]
Thank you the integration, works so smooth.

Is it possible to somehow translate or customise the responses from the integration (Zaptec's API)? My Home Assistant is setup in my native language, so I'd really like to translate some stuff if it's even possible.

For example on "Charger mode", I get `Waiting` or `Charging` as status, but I'd like to change those two.

**Comment by sveinse** [comment]
The Zaptec integration have its own set of translations. https://github.com/custom-components/zaptec/tree/master/custom_components/zaptec/translations . To translate the integration, a translated version of the json file has to be written. Please submit a pull request (preferably) or post the file in this issue.

**Comment by philsson** [comment]
The easy way out could be to make a template sensor with all your translations. Good enough is you dont do this for just one or a few sensors of course

**Comment by sunedall** [comment]
> The Zaptec integration have its own set of translations. https://github.com/custom-components/zaptec/tree/master/custom_components/zaptec/translations . To translate the integration, a translated version of the json file has to be written. Please submit a pull request (preferably) or post the file in this issue.

Thanks @sveinse. I came through that file as well, but the example I mentioned wasn't there (the status `Waiting`|`Charging`.

I saw it referenced in one of the Python files, but I'm on my phone currently. Will check later 🙂

**Comment by sunedall** [comment]
> The easy way out could be to make a template sensor with all your translations. Good enough if you dont do this for just one or a few sensors of course 

@philsson can you elaborate a bit more. I'm fairly new to HA 🙂

**Comment by philsson** [comment]
A template sensor basically is a sensor that you define. You can write your own logic. So basically you can define the if input (state of sensor x) is A, output should be B (your translation). 

I myself would do this with a Trigger template sensor.

**Comment by sveinse** [comment]
> > The Zaptec integration have its own set of translations. https://github.com/custom-components/zaptec/tree/master/custom_components/zaptec/translations . To translate the integration, a translated version of the json file has to be written. Please submit a pull request (preferably) or post the file in this issue.
> 
> Thanks @sveinse. I came through that file as well, but the example I mentioned wasn't there (the status `Waiting`|`Charging`.
> 
> I saw it referenced in one of the Python files, but I'm on my phone currently. Will check later 🙂

You are right. On closer inspection the "Charger mode" sensor is using the values provided by Zaptec. They are

```json
  "ChargerOperationModes": {
    "Unknown": 0,
    "Disconnected": 1,
    "Connected_Requesting": 2,
    "Connected_Charging": 3,
    "Connected_Finished": 5
  },
```

Perhaps its possible to set the language in the Zaptec portal and that it would change the above texts (but I somehow doubt it). So the next thing then would need to be to implement a translation service for these values, which I think is a fair request.

**Comment by sveinse** [comment]
@sunedall I've added PR #118 which adds the English translations for the states that you pointed out had no translation. I know this doesn't fix it for you (Danish?) but the translation file is now complete for it to be translated to other languages.

**Comment by sunedall** [comment]
@sveinse Wow, really fast response here! Didn't expect that 👏🏼👏🏼
Seems that my single example (`Waiting`) is left out from Zaptec's API, which is odd, but maybe just how it is:
```
  "ChargerOperationModes": {
    "Unknown": 0,
    "Disconnected": 1,
    "Connected_Requesting": 2,
    "Connected_Charging": 3,
    "Connected_Finished": 5
  },
```
I think I'll gradually translate line by line and check if they make sense in the context. Once I'm done, I maybe should consider doing my first contribution on Github 😉 (I will).

**Comment by sveinse** [comment]
@sunedall perhaps a little too fast, because "Waiting" is coming from the zaptec integration which I had missed. The PR is updated.

**Comment by sveinse** [comment]
@sunedall What should we do about this issue? Is the issue resolved? I'd like to propose that we close the issue and when you get around to making a Danish translation, we'll add a new issue and PR specifically for that.

**Comment by sunedall** [comment]
> @sunedall What should we do about this issue? Is the issue resolved? I'd like to propose that we close the issue and when you get around to making a Danish translation, we'll add a new issue and PR specifically for that.

@sveinse Makes sense to me! I'm not that fast currently due to personal schedules 😊
