### ISSUE TITLE
Current usage in realtime

### ISSUE THREAD

**Issue by keviny86** [custom-components/zaptec#121]
Hello!

Could anybody confirm for me if its possible to get current usage in watt for the total house in realtime?

**Comment by sveinse** [comment]
From zaptec? Then I would assume you mean Zaptec Pulse? Currently this integration have no integration with Zaptec Pulse unfortunately.

**Comment by keviny86** [comment]
From the sense load balancer.
https://www.zaptec.com/sv/laddningslosningar/zaptec-sense

What is zaptec pulse? do you mean tibber pulse?

**Comment by sveinse** [comment]
Of course, I meant Zaptec Sense, sorry. There is no current support for it either unfortunately. I simply don't know what data is possible to get from it through the Zaptec portal, as I don't have this equipment myself. The Zaptec docs does not mention it either so I don't quite know how to proceed unfortunately.
