### ISSUE TITLE
Anyone with issues with authorization?

### ISSUE THREAD

**Issue by sveinse** [custom-components/zaptec#122]
I'm having considerable problems getting my Zaptec to charge my EV (VW id.4) today. Normally works like a charm. I use the authorization feature in the Zaptec integration to do it, but this evening it completely refused to work. No errors, it just didn't start the charging. I tried using my registered RFID tag to no avail. Nor did a restart of the charger help.

Then I tried disabling the "Authorisation required" setting and after a restart of the Charger it started to work. But only for 2 minutes and then it stops again. Then it started again, but a much lower rate than specified (and I checked the Zaptec portal). This is a plot of the charge power.

<img width="695" alt="image" src="https://github.com/user-attachments/assets/12b635f0-29f8-4bb7-8d6b-927ddc838be1">

Anyone else with similar problems today?

**Comment by c0mplex1** [comment]
I just saw your post and immediately tested the authentication feature of my Zaptec integration, but I have no problems.
My car (Hyundai Kona) starts and continues to charge without any problem.

**Comment by sveinse** [comment]
Everything was completely ok when charging today, so I assume it was a hickup of either the EV charger or the car. Closing the issue. Thanks for checking up @c0mplex1
