### ISSUE TITLE
HA Core 2025.1 compatibility 

### ISSUE THREAD

**Issue by trichard-jabra** [custom-components/zaptec#124]
Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 11:34:26 AM (1 occurrences)
Last logged: 11:34:26 AM

TEMP_CELSIUS was used from zaptec, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'zaptec' custom integration

**Comment by sveinse** [comment]
This is fixed in #85 and pushed into master, but not yet released. Please update your integration to "master" if you want to try it out before it is released.
