### ISSUE TITLE
The "entity_id" option is deprecated

### ISSUE THREAD

**Issue by TheAlpiner** [custom-components/zaptec#13]
This might be my stupidity and not a code problem. but i check anyway. When testing the sensor example I get a deprecated warning when i try to identify my charger. I change the charger id to my id but since the entity_id is deprecated it ignores it. And the examples or readme files does not mention any other way to identfy the charger. Am i missing something :-)

**Comment by Hellowlol** [comment]
Just set it up using the UI.

**Comment by TheAlpiner** [comment]
Yepp, my mistake sorry. Working as a charm :-)
