### ISSUE TITLE
Dutch language?

### ISSUE THREAD

**Issue by c0mplex1** [custom-components/zaptec#133]
I translated the en.json file into Dutch language, for the Dutch speaking users. (if there are any)
Is there any interest in that?
[nl.json](https://github.com/user-attachments/files/17497585/nl.json)

**Comment by sveinse** [comment]
Yes, absolutely. Are you able to make it into a pull request?

**Comment by c0mplex1** [comment]
I would like to do that, I have tried, but I don't know how to do it.
I have never submitted a PR before.
[nl.json](https://github.com/user-attachments/files/17507960/nl.json) (updated)

**Comment by sveinse** [comment]
@c0mplex1, no worries, I can fix this for you. I'll create a PR and if you would review it that would be awesome

**Comment by c0mplex1** [comment]
I don't know how I did it, but after a lot of trying, I think I succeeded (I hope).

**Comment by sveinse** [comment]
Awesome. Just as a friendly tip @c0mplex1: Issues like this one is usually not closed until after the PR have been implemented. This way its possible to track progress.

**Comment by FluGanz** [comment]
[sv_se.json](https://github.com/user-attachments/files/17554541/sv_se.json)
Here is a Swedish translation aswell. I'm not able to do a PR, like c0mplex1 I have never done that ether
