### ISSUE TITLE
Cannot setup zaptec (TypeError: 'NoneType' object is not subscriptable)

### ISSUE THREAD

**Issue by roflmao** [custom-components/zaptec#14]
Got a new charger (Zaptec Pro iirc) setup today, only with accesslevel "User", dont know if this is causing the issues

Version: 0.0.3

Logs:
```
2021-10-20 10:57:11 ERROR (MainThread) [custom_components.zaptec.api] Could not get info from https://api.zaptec.com/api/installation: 
2021-10-20 10:57:11 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Zaptec for zaptec
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/zaptec/__init__.py", line 68, in async_setup_entry
    await _dry_setup(hass, entry.data)
  File "/config/custom_components/zaptec/__init__.py", line 44, in _dry_setup
    await acc.build()
  File "/config/custom_components/zaptec/api.py", line 438, in build
    for data in installations["Data"]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Hellowlol** [comment]
I have tested signalr connect now and unfortunately, the only info I get there "live" is total_charge_power_session which is pretty useless IMO :/

Example output from the signalr connection:

```
{"type":1,"target":"notifyObservation","arguments":[
    "ZCHXXXXXX",
    {
      "ObservationId": 553,
      "ObservedAt": "2022-02-07T20:52:01.773343Z",
      "Value": "24.506",
      "OldValue": "24.444"
    }]}
```

It's strange that the integration didn't throw an exception. Do you mind turning on debug logging on the component and posting the log?

**Comment by sveinse** [comment]
In my experience a Zaptec user with the unprivileged access rights "User" is very limited. Even on portal.zaptec.com, there isn't much that user is able to do. The user can observe the status of charging through the API, but it doesn't seem possible to interact with the charger. I have tried that on my Zaptec Go and the commands just bounces on me.

The newest version of zaptec that I'm working on, tracked in PR #56 fixes the issue of using zaptec with an unprivileged user. It is at beta test in my fork at https://github.com/sveinse/zaptec and is installable via HACS (yet I'd be careful on production environments). See the URL for instructions if you want to give it a go. I'm grateful for all feedback I can get.

**Comment by sveinse** [comment]
The 0.7.0 have now been released which works when being used with unprivileged user.

Is this issue still valid? If it isn't, I'd like to close the issue.
