### ISSUE TITLE
Zaptec Go, can't resume charging

### ISSUE THREAD

**Issue by Silkjaer** [custom-components/zaptec#144]
Have had some unreliability the past weeks, where charging didn't start as it should, or in some cases didn't stop as it should.

Automations runs at the right times, and I have been setting the installation available current AND charger max current to start/stop charging.

Lately I realized that it doesn't work manually changing max current on the charger – nothing happens. So I've changed to only set available current. But no matter what available current is, the charger remains in "charging paused" state. Resume charging requests times out, and resuming charging through Zaptec portal also fails.

Have anyone else experienced issues like this? 

Zaptec Go FW is 2.4.1.8

**Comment by sveinse** [comment]
I had some problems a couple of weeks back #122 but it passed.

It doesn't bode well if the same behavior is observed through the Zaptec portal. Then this sounds like a central Zaptec issue.

Note there are three sliders to adjust charging current in zaptec: "Available current" in the integration device, "Charger max current" and "Changer min current" in the charger device. When I charge I only adjust the "Available current" and leaves min and max alone. I also observe that Zaptec reset the "Available current" to maximum value once per day or so.

**Comment by Silkjaer** [comment]
Yea, I'll give it some time and see if it changes. Right now I have no way to start charging. Cloud managed devices 🤦‍♂️

**Comment by sveinse** [comment]
I think I would reach out to Zaptec support if you are completely cut out of being able to charge. Good luck!

**Comment by Silkjaer** [comment]
Just pulled the power and switched it back on, and seems like it came back alright. I thought I had already restarted it, but portal/app clearly didn't restart it when I asked it to. 

Thanks
