### ISSUE TITLE
Missing chardet

### ISSUE THREAD

**Issue by Olen** [custom-components/zaptec#15]
After upgrade to 2021.12.9
```
ERROR (MainThread) [homeassistant.setup] Setup failed for zaptec: Unable to import component: No module named 'chardet'
```

Seems like HA is using cchardet, and they _should_ be pretty compatible, so maybe just a
`import cchardet as chardet` 
would do the trick...

**Comment by Olen** [comment]
Looking a bit further, it does not seem like chardet is actually being used in this component, so it could probably just be removed...

**Comment by Hellowlol** [comment]
Your right. It isn’t used anymore. I’ll fix that. Thanks for the report.

**Comment by TheAlpiner** [comment]
Is there are workaround for this ? I ggot teh same problem :-)

**Comment by Olen** [comment]
Just remove the line 
```
import chardet
```
from `custom_components/zaptec/api.py` 

And restart HA

**Comment by TheAlpiner** [comment]
> Just remove the line
> 
> ```
> import chardet
> ```
> 
> from `custom_components/zaptec/api.py`
> 
> And restart HA

Worked like a charm... But that i should have figured out myself :-)

**Comment by Hellowlol** [comment]
Fixed
