### ISSUE TITLE
Problem with the entity 'session total charge' in v 0.7.2

### ISSUE THREAD

**Issue by Oliv4nder** [custom-components/zaptec#152]
I use the entity 'XX Session total charge' to keep track on the charge cost by adding it to the energy tab in home assistant. It has worked great until 0.7.2. 

In 0.7.2 it behaves the same as before as long as I'm charging the car and it is plugged in.  But when the car is disconnected from the charger the value in the energy tab gets negative with the same value as the car was charged with. 

Example: I charge 5kwh between 1am to 2am to the cost of 5 euro and 5kwh more 2am to 3am to the cost of 7 euro. Total charge is then 10kwh and 12 euro reported in the energy tab. 0.7.1 and 0.7.2 behaves the same during this phase.  But when I disconnect the car at 1pm when the hourly rate is 1,5 euro/kwh the energy tab will report -10kwh and -15 euro with 0.7.2. In 0.7.1 the entity is changed to 0 and no negative values reported in the energy tab.

I have tried the enitity 'xx Energy meter' instead but the cost from this entity is reported one hour late witch will give the wrong cost so that is not working either. 

I have downgraded to 0.7.1 since I have no issues with 0.7.1 and hope there can be a fix for this problem in a future release or if it is some configuration I need to change to get it working in 0.7.2

**Comment by sveinse** [comment]
I believe this is already fixed in #145 . It is implemented in master, but it has not yet been released. If you can try out master to see if this fixes the issues that would be swell.

**Comment by Oliv4nder** [comment]
> I believe this is already fixed in #145 . It is implemented in master, but it has not yet been released. If you can try out master to see if this fixes the issues that would be swell.

I'ill try out the master and report back after I have charged the car in 1 or 2 days.
