### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype

### ISSUE THREAD

**Issue by freeverbier** [custom-components/zaptec#18]
Type of charger : Zaptec Pro
Role into the portal : User / Owner / Service

```
Source: custom_components/zaptec/api.py:407
Integration: zaptec (docs)
First occurred: 22:28:32 (1 occurrences)
Last logged: 22:28:32

Could not get info from [https://api.zaptec.com/api/circuits/{self.id}/](https://api.zaptec.com/api/circuits/%7Bself.id%7D/): 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https:// api.zaptec.com/api/circuits/%7Bself.id%7D/')
```

**Comment by freeverbier** [comment]
How can i do that ? I run the HA OS and with the SSH access i don't have access to python or python3.

I saw in the attributes of my entity all parameters i need

<img width="378" alt="image" src="https://user-images.githubusercontent.com/101563280/159799769-c74c6dd1-5c72-4b1f-bfd9-1d6fc213794c.png">

**Comment by Hellowlol** [comment]
You can run it from any computer that has Python installed. But the simplest option would be to turn on debugg logging. Maybe I get what i need from that
