### ISSUE TITLE
Zaptec PRO charger stopped working after update

### ISSUE THREAD

**Issue by mrfrostfire** [custom-components/zaptec#19]
Version 0.0.2 and forward is using acc.installations to get the chargers, while the old version was using acc.chargers.
Zaptec GO chargers is added as installations, while Zaptec PRO chargers are not.
I have a Zaptec PRO charger (not shared, it's all mine) and it was working with the previous version, but after this update. it's not.
There is alos no option for me top change the version back to pre-0.0.2 since the only releases are 0.0.2, 0.0.3 and master.

![image](https://user-images.githubusercontent.com/3914832/161620889-1147e720-066a-4e87-82b7-281197123788.png)

**Comment by Hellowlol** [comment]
You have to dig in the commit history to find the correct one and grab it.

**Comment by mrfrostfire** [comment]
I did, but then I decided to fix the code instead :) got it working, havent tried aby commands, but it shows me all the info. 
I’ll make a pr tomorrow

**Comment by Hellowlol** [comment]
I also have a unpublished branch to support live updates on charger’s with only user role. I have no idea if it works on pro. Can you post a debug log?

**Comment by mrfrostfire** [comment]
There wasn't really much help in the debug log. The issue is that zaptec pro chargers has a circuit and installation id on the charger entity BUT the installation and circuits can't be reached using the api. This means that when you query the api for installations, it returns empty, and no sensors are added. I am both user and owner on this charger, yet there is not even an installation tab in their portal, and when trying the api from their swagger using the installationid from the charger, I get a 403 or 500 back. It appears that they simply don't support PRO chargers in that way.
PRO seems to be set up differently than GO which is also very striking as you can Add a GO charger yourself, but only authorized installers are allowed to add a PRO charger. 
I'll make a PR of the codechanges I made anyway, use it if you will :) 
Also got rid of some deprecationwarnings while I was at it.

**Comment by mrfrostfire** [comment]
#20
