### ISSUE TITLE
Configuration manual

### ISSUE THREAD

**Issue by romhug** [custom-components/zaptec#22]
Hi Steffen

I just started to use Homeassistant. One of the reasons to start a HA project is the fact, that i have a Zaptec go charger that I want to integrate into my Smarthome. 

I was able to install the zaptec repository on my HA with HACS. But I don't understand, how to setup to use this integration.  May I ask you to give me a hint, what I have to do, to bring this integration alive? 

Thank you so much for your help. 
BR Roman

**Comment by Hellowlol** [comment]
The integration is broken atm. You could try to install the pr. I think that fixed it

**Comment by romhug** [comment]
what do you mean with PR?

**Comment by kdrost1** [comment]
Got this meassage when i try to configure the component  
![image](https://user-images.githubusercontent.com/11019670/167080480-76bf6e62-c3fe-47b8-a0c4-8c44888716b6.png)

**Comment by romhug** [comment]
> You could try to install the pr. I think that fixed it

What do you mean with this?

**Comment by Hellowlol** [comment]
Update to the latest version
