### ISSUE TITLE
Only status showing is Charging/not charging

### ISSUE THREAD

**Issue by abelone91** [custom-components/zaptec#24]
Hello, 

Awesome to have found that your guys worked on this integration! 

I ran the int. on my homeassisant, installation and login went painlessly. However, the only Entity ID i am getting is whether the charger is in use or not. All the other information is displayed under attributes in the Entity. What could be the reason?

**Comment by Hellowlol** [comment]
Cus its designed that way. I dont want to add a sensor for every attribute.

**Comment by abelone91** [comment]
Really impressive work!
