### ISSUE TITLE
Could not get info from https://api.zaptec.com/api/installation/bf68a41d-d2f9-44f5-bfc6-20bf42e645a8:

### ISSUE THREAD

**Issue by Bluhme1** [custom-components/zaptec#29]
@Hellowlol Are you still maintaining this?

I use it on a daily basis and am very fond of it. I think it is a very valuable "tool" in my dealing with the electric car.
So first of all a big thank you to you 

Every day I get the following errors in the log

Could not get info from https://api.zaptec.com/api/installation/bf68a41d-d2f9-44f5-bfc6-20bf42e645a8:
Could not get info from https://api.zaptec.com/api/chargerFirmware/installation/bf68a41d-d2f9-44f5-bfc6-20bf42e645a8:
Could not get info from https://api.zaptec.com/api/chargers/d740fcdd-c244-4215-b576-e607193f5e27/state:

The integration seems to work but the errors comes back again and again. Perhaps something to do wit a little shaky API from Zaptec as there have been issues lately?

Anyway here is my log

[zaptec.txt](https://github.com/custom-components/zaptec/files/10577300/zaptec.txt)

Thanks in advance

Lars. Denmark

**Comment by Hellowlol** [comment]
Yeah, i still maintain it. It’s just a hassle to test and I don’t use this my self. I only have a easee charger. It something breaks, I’ll fix it

**Comment by sveinse** [comment]
Any updates on this issue? Zaptec 0.7.0 has now been released which significantly improves how data is fetched from Zaptec Portal. Does this version fix your issue @Bluhme1 ? If this issue is old and outdated, I'd like to close it. Thanks.
