### ISSUE TITLE
Får bare opp 3 entiteter og egentlig ikke mye info mer.

### ISSUE THREAD

**Issue by magne74** [custom-components/zaptec#32]
Hei @Hellowlol 

Har installert zaptec-integrasjonen din i HA. Før fikk jeg ut mye info og kunne vel også tyre laderen. Den tiden er forbi. Får kun opp det vedlagt bilde viser. To av entitetene har ingen info i det hele tatt, den siste gir info om laderen lader, koblet fra osv. Men ingenting annet. Er integrasjonen gravlagt. Ser den ikke er vedlikeholdt på en god stund? Eller er det noe å gjøre med den?

På forhånd takk for hjelpen.

<img width="1097" alt="Skjermbilde 2023-05-03 kl  13 17 41" src="https://user-images.githubusercontent.com/111948595/235903035-e23712f7-2856-4fe0-98c2-9befc674c7a5.png">

**Comment by Hellowlol** [comment]
Hei,

Jeg bruker ikke integrasjonen selv da jeg ikke har denne laderen selv. Jeg skal se om jeg kan få lånt meg en login så jeg kan teste den.

**Comment by magne74** [comment]
Du kan låne min.Sendt fra min iPhone3. mai 2023 kl. 22:06 skrev Steffen Fredriksen ***@***.***>:﻿
Hei,
Jeg bruker ikke integrasjonen selv da jeg ikke har denne laderen selv. Jeg skal se om jeg kan få lånt meg en login så jeg kan teste den.

**Comment by danielkihlgren** [comment]
I have the same that it’s only 3 devices. Each device has one sensor each with a lot of attributes where most info can be found. No switches are exposed so I can’t control anything.

I’m a new user so I don’t know how it used to be. I’m trying to get a hang of the code base but python is not my primary language and I haven’t done any HA plugins so it will take some time. I did manage to patch the code since I had problems with ssl issues when the plugin called the services. If those problems was only for me with my installation I don’t know.

**Comment by odin-** [comment]
Same issue for me. Installed my Zaptec today. If possible I would also like to control more so I can implement charging scheme in HA.

**Comment by Hellowlol** [comment]
@magne74 I justed with with a "old" charger. What charger and what access level do you have to the charger and the installation? You can see your access level in the portal.
![image](https://github.com/custom-components/zaptec/assets/1214134/27737e87-1bb1-4e46-9b7b-551b12f0b6ff)
@danielkihlgren There are already services so can control simple stuff like start and stop. Use the services tab in HA to see them. What do you need to control/what switches are missing?
I still need to implement change or current.

**Comment by Hellowlol** [comment]
If someone wants to lend me access to their go charger please reach out to hellowlol1 at gmail.com

**Comment by iBlow** [comment]
Hi @Hellowlol 

I got the same issue only 3 devices and 3 entities. Installed it yesterday, so dont now what is supposed to be shown but i supposed it should be something like I have on easee (25 entities)?

![zaptec 3 entities](https://github.com/custom-components/zaptec/assets/33761059/828def70-955b-407b-975a-485bdc9c4bf0)

![Easee 25 entities](https://github.com/custom-components/zaptec/assets/33761059/f708f7cb-efd8-4f7b-a9ed-f6beccae3d6d)

**Comment by Hellowlol** [comment]
No its not. A user would typically have access to one charger, one circute and one installation. Data is added as a attribute of sensor.
