### ISSUE TITLE
lovelace examples | where's the data coming from?

### ISSUE THREAD

**Issue by Symbiot78** [custom-components/zaptec#37]
Was looking at the examples.
Most of the data used in the examples is no-where to be found in any of the 3 devices/entities that is show in the integration.
for instance the template sensor which uses this:

"{{ state_attr('sensor.zaptec_zch000000', 'total_charge_power_session') | round(0) }}"

just throws an error. I changed the sensor name of course.
looking at the sensor.zaptec.<myzaptecID> I cannot see any total_charge_power_session.

I am looking to get the usage data from zaptec so I can see daily, weekly, monthly.. like in the app.

The sensor does showed 'completed_sessions' which contains some data.. and I can get "last charge" data there by extrapolating it like this:

  sensor:
    - name: zaptec_last_charge
      device_class: energy
      state_class: total
      unit_of_measurement: kWh
      state: >-
          {{ (state_attr( 'sensor.zaptec_charger_zap008009', 'completed_session') | from_json).Energy }}

But I can't get weekly and monthly.

Am I missing something?

**Comment by Symbiot78** [comment]
Hey
It’s a Zaptec Go.

**Comment by KLucky13** [comment]
I also have zaptec go and have have 3 entities available spread over 3 devices. In the app there is much more info to be found but is not found in this integration. Which makes the integration pretty much useless for me..

This is all I see:
-sensor.zaptec_charger_zap1.....
-sensor.zaptec_circute_964c4866_9......
-sensor.zaptec_installation_15e701f9_43......

**Comment by Hellowlol** [comment]
@KLucky13 good thing you dont need to use it, just uninstall!

**Comment by philsson** [comment]
> I also have zaptec go and have have 3 entities available spread over 3 devices. In the app there is much more info to be found but is not found in this integration. Which makes the integration pretty much useless for me..
> 
> This is all I see: -sensor.zaptec_charger_zap1..... -sensor.zaptec_circute_964c4866_9...... -sensor.zaptec_installation_15e701f9_43......

I see too many people complaining about this. Check the attributes and you'll see that there is a ton of stuff. Also don't miss the services. I really think a switch should be included as an alternative to the services, but this is easy enough to fix on your own.

**Comment by KLucky13** [comment]
> > I also have zaptec go and have have 3 entities available spread over 3 devices. In the app there is much more info to be found but is not found in this integration. Which makes the integration pretty much useless for me..
> > This is all I see: -sensor.zaptec_charger_zap1..... -sensor.zaptec_circute_964c4866_9...... -sensor.zaptec_installation_15e701f9_43......
> 
> I see too many people complaining about this. Check the attributes and you'll see that there is a ton of stuff. Also don't miss the services. I really think a switch should be included as an alternative to the services, but this is easy enough to fix on your own.

Thanks for clarifying this, I'll have a look. I'm used to seeing everything as an entity so I was not aware of this.

**Comment by sveinse** [comment]
Is everything in good order @Symbiot78 , can we close this issue?

**Comment by Symbiot78** [comment]
Hi @sveinse - i Think its status quo. I am still not seeing the data I want nor do I know how to get it. So I guess my original question stands.

**Comment by sveinse** [comment]
@Symbiot78 looking at your initial question, you want to get charge statistics from Zaptec? Unfortunately, the zaptec integration doesn't have this as the data from the Zaptec API doesn't contain it. Getting charge statistics from the Zaptec cloud is possible with its own request, but it has to be implemented as a separate function and I'm not sure how this could be integrated into HA in a good way. Any suggestions?
