### ISSUE TITLE
Sensor and switch doesn't update (regression)

### ISSUE THREAD

**Issue by sveinse** [custom-components/zaptec#50]
The `zaptec_charger_*` sensor and the `zaptec_*_switch` are extremely slow to update its state, maybe not at all. I waited over 2 hours and the field doesn't update without restarting. The previous version was immediate.

Technically they use the attribute `operating_mode`, which comes from the (static?) attrs read from the API at build. The previous implementation used `charger_operation_mode`, which is read from state (stateID 710) and thus updated. Might the problem here be that the latter is updated on the event notifications, while the former is not?

**Comment by Hellowlol** [comment]
That might be the case. Can you a dump from using the API to show what attributes you have available for your charger?

**Comment by sveinse** [comment]
You can find a redacted data dump from the API here: https://gist.github.com/sveinse/6b59a2b4236cd2ccf561646e889465d6 - each redaction are numbered, so you can cross correlate them

**Comment by sveinse** [comment]
Will be fixed by PR #56

**Comment by sveinse** [comment]
This is fixed in v0.7.0. Closing issue
