### ISSUE TITLE
Are there any known problems with Home Assistant in docker?

### ISSUE THREAD

**Issue by bitfieldfarm** [custom-components/zaptec#59]
I can't setup configuration. I get the following error:

 Konfigurasjonsflyt kunne ikke lastes inn: 500 Internal Server Error Server got itself in trouble

**Comment by MartinLorenzen** [comment]
I got the exact same error when trying to install the integration on Home Assistant OS running in a VM on Proxmox.

`Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`

**Comment by bitfieldfarm** [comment]
ChatGPT suggested running `pip install azure-servicebus==7.0.1` based on my logs.

Bottom part the output from this suggestion:

```
      subprocess.CalledProcessError: Command 'cmake /tmp/pip-install-e1a51u42/uamqp_c4da6adbdc154190930fe771ebc766d6/src/vendor/azure-uamqp-c/ -G "Unix Makefiles" -Duse_openssl:bool=ON -Duse_default_uuid:bool=ON  -Duse_builtin_httpapi:bool=ON  -Dskip_samples:bool=ON -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for uamqp
Failed to build uamqp
ERROR: Could not build wheels for uamqp, which is required to install pyproject.toml-based projects
```

Maybe something with the docker environment?

**Comment by MartinLorenzen** [comment]
I just installed the beta version of the integration and that solved the problem.
Check this issue:
https://github.com/custom-components/zaptec/issues/34

**Comment by bitfieldfarm** [comment]
Yep. That worked
