### ISSUE TITLE
In a 3 phase charging session, is it OK to change phases individually?

### ISSUE THREAD

**Issue by svenakela** [custom-components/zaptec#69]
This is not an issue but rather a quest for clarification.

In the readme the [3 phase current adjustment](https://github.com/custom-components/zaptec#3-phase-current-adjustment) part mentions setting each phase individually. Is it actually OK to set phases individually during a charge, and if doing so can they be used with different limits?

My impression is that a charger should have the same limit on all phases during a three phase session. i.e. 12/12/12 A. But this also means that if one phase is overloaded all three phases should be adjusted to lower the current dictated by that one overloaded phase.
If it is OK to set different limits (can an inboard charger handle it, is it ok according to standards?), that would mean that only the overloaded phase can be lowered and the other two phases use a higher draw, like 8/12/12 A.

**Comment by sveinse** [comment]
Technically it is fine to set individual current levels, e.g. like 8/12/12. The charger supports this. However, the actual current consumption is made by the car, so it must support this. I've seen cases with cars that they don't draw unequal currents on the three phases, but others do. If you set it to unequal values, my experience is that these cars just settle on consuming the lowest value for all phases.
