### ISSUE TITLE
Enable statistics for the charge power and possibly other entities

### ISSUE THREAD

**Issue by JonathanJorstad** [custom-components/zaptec#75]
When trying to add a graph card for the charge power (ID: sensor.ladestasjon_1_charge_power), it is not available since home assistant complains about how the entity is defined: it is "caused by a bug in the integration providing the entity. Integrations need to configure their entities correctly so Home Assistant knows that we need to track statistics for it and how. Open an issue with the author of the integration and link them to https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics "

So a feature request would be to specify this for relevant entities such as charing power, unless it destroys other functionality.

**Comment by sveinse** [comment]
The lastest verion in "master" (version 0.7.1a5) contains a fix for the statistics issue. Please install this version and report back if this fixes your problem. (When we've verified it, we can go a head and release 0.7.1 as a release.)

**Comment by JonathanJorstad** [comment]
Can confirm that I can now add for instance charge power as a statistic. It
allows for charge power to be plotted together with other data such as
total house power consumption etc.

fre. 29. des. 2023, 17:02 skrev Svein Seldal ***@***.***>:
