### ISSUE TITLE
charger-card template?

### ISSUE THREAD

**Issue by aunefyren** [custom-components/zaptec#82]
Hello, I am writing this as an issue as I did not see a "discussions" pane. Feel free to close this if it interferes with development. 

I have setup my Zaptec integration and it seems to work nicely! Well done creating this.

I would personally like to use a nice custom card on my Home Assistant page, as user interfaces is not my strong suit. This one called `charger-card` is a very [popular smart charger card](https://github.com/tmjo/charger-card), which is highly regarded it seems. They don't have integrated Zaptec support, which is understandable, but support custom configurations and [templates can be made](https://github.com/tmjo/charger-card/wiki/How-to-add-template-for-new-brand) for different brands. 

Does anyone have any experience with this, or perhaps have already done something similar. Though I should ask before I do a deep dive into this.

Thanks!

**Comment by sveinse** [comment]
It is a really good idea to add Zaptec support to `charger-card`. I have barely glanced at it, but it should be doable. I've created https://github.com/sveinse/charger-card-zaptec. I don't know if I can commit to doing this yet, but its worth a look.

**Comment by sveinse** [comment]
@aunefyren Can we close this issue as the card has been merged to tmjo/charger-card?

**Comment by aunefyren** [comment]
I suppose so. My intial pull request is far from perfect, but I guess people can contribute at https://github.com/sveinse/charger-card-zaptec if they want to expand on it.
