### ISSUE TITLE
Got update for unknown charger id 00000000-0000-0000-0000-000000000000

### ISSUE THREAD

**Issue by jenscski** [custom-components/zaptec#84]
In the log i find this,

Is this a bug in the component, or something with my installation?

```
Logger: custom_components.zaptec.api
Source: custom_components/zaptec/api.py:1073
Integration: Zaptec EV charger ([documentation](https://github.com/custom-components/zaptec))
First occurred: 7. januar 2024 kl. 15:33:35 (560 occurrences)
Last logged: 13:10:16

Got update for unknown charger id 00000000-0000-0000-0000-000000000000
```

**Comment by sveinse** [comment]
Looking at the code, this warning is caused by Zaptec portal/cloud pushing a data update for a non-existing charger. So its Zaptec that does something new or strange here. If they have started pushing updates to a `00000...` charger ID, perhaps we should filter away this particular warning?

**Comment by jenscski** [comment]
Same setup as I have, so something is different on my side then ...

But, I guess it's okay to filter out chargers with an "empty" id

Anything I can do to test?
Is it an easy way to e.g. use Postman to call Zaptec API to see what's returned when using my credentials?

**Comment by sveinse** [comment]
> Anything I can do to test? Is it an easy way to e.g. use Postman to call Zaptec API to see what's returned when using my credentials?

For the pure web API stuff this is a good place to test things out: https://api.zaptec.com/help/index.html#/. However the above issue is related to streaming, which is not accessible from the Swagger interface.

**Comment by sveinse** [comment]
Is this a problem which is still observed? @jenscski

**Comment by jenscski** [comment]
Yes, I'm still seeing this in the log, at version 0.7.1

```
Logger: custom_components.zaptec.api
Kilde: custom_components/zaptec/api.py:1073
integrasjon: Zaptec EV charger ([dokumentasjon](https://github.com/custom-components/zaptec))
Førs oppstått: 19. september 2024 kl. 10:06:55 (156 hendelser)
Sist logget: 07:17:16

Got update for unknown charger id 00000000-0000-0000-0000-000000000000
```

**Comment by jenscski** [comment]
I have version v0.7.1 installed, but I'm still seeing the warning, but I don't think it's causing any problems - just log messages

```
Logger: custom_components.zaptec.api
Kilde: custom_components/zaptec/api.py:1073
integrasjon: Zaptec EV charger ([dokumentasjon](https://github.com/custom-components/zaptec))
Førs oppstått: 18. oktober 2024 kl. 21:16:06 (1891 hendelser)
Sist logget: 20:50:37

Got update for unknown charger id 00000000-0000-0000-0000-000000000000
```

**Comment by sveinse** [comment]
Can you please try the beta version "master" and see if the items in the logs disappear? @jenscski

**Comment by sveinse** [comment]
It seems HACS have removed the ability to download master. I'll see what I can do.

**Comment by jenscski** [comment]
I think I have managed to update to master, running versjon 0.7.2b1.

Will report later if log is empty

**Comment by jenscski** [comment]
No log entries for 10 hours, so guessing it's fixed.
