### ISSUE TITLE
Session_total_charge is not strictly increasing warning

### ISSUE THREAD

**Issue by sveinse** [custom-components/zaptec#86]
Observed in version 0.7.1

Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:288
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 02:55:10 (1 occurrences)
Last logged: 02:55:10

Entity sensor.sol_session_total_charge from integration zaptec has state class total_increasing, but its state is not strictly increasing. Triggered by state 22.991 (23.493) with last_updated set to 2024-01-09T01:53:10.747638+00:00. Please report it to the author of the 'zaptec' custom integration

**Comment by Bluhme1** [comment]
@sveinse : I haven't got that warning (where do you see that?). Maybe the key="total_charge_power_session" should be set to MEASUREMENT instead? It can still be included in the Energy Panel. I think that was the main reason why I suggested TOTAL_INCREASING, but now it is possible with the State_Class MEASUREMENT.
I can't see whether the warning has disappeared as I don't know where to see it.
/Lars

**Comment by sveinse** [comment]
@Bluhme1 We have another issue #87 where MEASUREMENT were used for energy which is quote "an impossibility". According to HA, energy is not an instantaneous measurement and cannot be a measurement. So HA requires energy sensors to be TOTAL or TOTAL_INCREASING.

If it turns out that we cannot use anything, we might need to raise this problem to HA. If MEASUREMENT cannot be used with energy sensors and TOTAL cannot be used because it cannot be shown in statistics and finally TOTAL_INCREASING cannot be used because the figure doesn't always increasing, then we have a problem....

**Comment by Bluhme1** [comment]
@sveinse . Hmm. I on my way to a conference but will be back for the weekend. Should we try TOTAL and see if the warning disappear?

**Comment by Bluhme1** [comment]
@sveinse Have tried with TOTAL. It seems that the sensor might be able to collect long-term statistics with that. 
I cannot try charging until the weekend to see what actually happens when there will be values to the sensor.
I have set  key="total_charge_power_session" and key="completed_session.Energy" to TOTAL and left  key="signed_meter_value_kwh" to TOTAL_INCREASING. It seems the most logical thing to me.
But sometimes HA isn't logical
