### ISSUE TITLE
Delete device

### ISSUE THREAD

**Issue by Fredrik81** [custom-components/zaptec#89]
It would be good to be able to delete old devices.
I still se pre 0.7 devices and now I changed my charger I still see the old charger.

**Comment by sveinse** [comment]
I believe this is a feature of HA. I've been able to remove stale lingering devices by uninstalling zaptec and reinstall it again. This removes the old devices.

**Comment by Fredrik81** [comment]
Yes I know that way. I see some integrations auto-remove stale devices. 

https://community.home-assistant.io/t/how-can-i-delete-devices-i-dont-want-in-ha/236080/18

**Comment by Fredrik81** [comment]
Thanks!
