### ISSUE TITLE
Available current not equal to allocated current for a single charger installation

### ISSUE THREAD

**Issue by medisinmannen** [custom-components/zaptec#91]
This integration is awesome, but im struggling to use it because i dont have coding experience. 

My issue is the "Available current" for the charger which ive set to maximum current draw for my installation(1 charger).
Zaptec set the "allocated current" to 6A lower than my available current. 

Is this because minimum allocated current is 6A, as if my installation has 2 chargers? 

![allocated vs available](https://github.com/custom-components/zaptec/assets/107512732/e6bdeefe-a3fa-4723-9835-6577bab6e54e)

Another suggestion/wish is to add a few examples of cards to present the integration(because i dont know coding). 
Such as a slider with the range of 6-32A or format it to "x kW" to "xx kW".

**Comment by sveinse** [comment]
What is the setting for the "Charger max current" and "Charger min current" found in the charger device?

> Another suggestion/wish is to add a few examples of cards to present the integration(because i dont know coding).
> Such as a slider with the range of 6-32A or format it to "x kW" to "xx kW".

I think that is a great idea. I have somewhat the same problem: I actively limit the number of kW the house is consuming by regulating the available current to the zaptec charger. I don't really care about the current, I care about kW. -- That said, the calculation from kW to amps is depending on a few other variables (1 or 3-phase, voltage), so the entity would be a derived/calculated value and not natively as zaptec wants it. I'm not sure what's best to do here. Is this where blueprints migh help?

**Comment by medisinmannen** [comment]
> What is the setting for the "Charger max current" and "Charger min current" found in the charger device?

32A & 6A. Changing these values does not affected the mismatch.

**A blueprint would be very helpful.** 
Im so lost at coding that i struggle to change the "Available current" by other means than a slider. 
I tried changing the value by node-red but failed. Created a helper(with defined kW charging), but my skill limits me to change "Available current". 

Down the road Im trying to implement a strategy to check my current hour consumption every 30 min and adjust the charging amps so im under a defined level pr hour. For other than Norwegians, this is a rate imposed by system operator - higher cost for high hourly consumption.

**Comment by svenakela** [comment]
> 
> Down the road Im trying to implement a strategy to check my current hour consumption every 30 min and adjust the charging amps so im under a defined level pr hour. For other than Norwegians, this is a rate imposed by system operator - higher cost for high hourly consumption.

You can use this blueprint as a start, if you want to do balancing. You can set your available max current as the charger fuse and it would stay under your threshold.
https://github.com/svenakela/ha/tree/main/zaptec

**Comment by sveinse** [comment]
What is the status of this issue? Did you get help you needed @medisinmannen ? If not, please try to write out a specific question. Otherwise I'd like to close the issue.
