### ISSUE TITLE
Cable Lock binary sensor has inverted value

### ISSUE THREAD

**Issue by NorseJedi** [custom-components/zaptec#95]
It appears that the dedicated binary sensor ```binary_sensor.(name)_permanent_cable_lock``` is inverted, and is always the opposite of the corresponding value in ```binary_sensor.(name)_charger``` attribute ```permanent_cable_lock```.

In other words, when the attribute on the charger sensor is ```true``` the dedicated cable lock sensor is ```"off"```, and when the attribute on the charger is ```false``` the dedicated cable lock sensor is ```"on"```.

The charger attribute matches the setting in the Zaptec mobile app, while the dedicated sensor does not.

**Comment by sveinse** [comment]
This is due that the entity use the HA predefined setup for lock where the signal needs to be inverted. It use the device class `BinarySensorDeviceClass.LOCK` where On (`true`) means open (unlocked), Off (`false`) means closed (locked). The icons will be wrong if they are inverted.

**Comment by sveinse** [comment]
Any updates @NorseJedi ? I'd like to close the issue if this answer was sufficient.

**Comment by NorseJedi** [comment]
My apologies, I didn't think you were expecting an update from me since this is the expected behaviour and not a bug, so yes, you can close the issue. Thank you :)
