### ISSUE TITLE
Set max Max charger current in the charger object

### ISSUE THREAD

**Issue by NikeHome** [custom-components/zaptec#96]
Hi, 

First of all, thanks for a great integration! Very nice coding! 

I have 2 Zaptec Go with installer rights in my home and need to control the max current on a charger level. 

I assume I need to set "Charger max current" in the charger object, but can't figure out how to do this. 

If its possible via this integration, could you tell me how to do it? If it's not possible, would it be possible to implement it?

I can't use authorization as that method is already in use and controlled by my electricity company in order to get a lower charging price. 

I wrote a simple custom component to charge at low spot price but have no means of controlling when to charge car 1 vs car 2 based on my prioritization preference. 

Thanks in advance!

**Comment by sveinse** [comment]
If you go to Settings -> Devices & services -> Devices and then locate the device for the charger itself, the device page should contain a Configuration section that looks something like below. This is where it is possible to configure the max and min current that the charger is using.

<img width="253" alt="image" src="https://github.com/custom-components/zaptec/assets/13770135/fdddaf22-e128-4ab0-9a5c-d22a5188f5f8">

**Comment by NikeHome** [comment]
Ah, this will solve my problem. 

Found the charger object current settings according to your response above. This will make it possible to control the chargers individually. Will try it out!

Many thanks Sveinse!
