### ISSUE TITLE
Energy Meeter reporting frequency

### ISSUE THREAD

**Issue by NikeHome** [custom-components/zaptec#97]
Many thanks for a great Zaptec Integration!

I'm using the "Energy Meeter" reported by the Zaptec component in a custom component to calculate the cost for charging, solar, battery and house consumption. 

The "Energy Meeter" is only updating just after every new hour, is it possible to update the frequency of this reporting or is it maybe controlled by Zaptec Cloud?

Many thanks in advance!

**Comment by sveinse** [comment]
By default the Zaptec integration cloud polls the cloud every 30 or 60 seconds, so if the data isn't updated more frequent it's because Zaptec cloud doesn't update the data more often.

**Comment by NikeHome** [comment]
Many thanks for your resonse Sveinse!

Then it is like it is, I will adapt my calculations so the energy reading is applied in the past hour instead. 

All the best!
