### ISSUE TITLE
Logo color

### ISSUE THREAD

**Issue by jseedorff** [custom-components/zaptec#98]
Great plug-in, works perfect. Thanks!

Only small issue is logo color. It's hard to see on a dark background.

![image](https://github.com/custom-components/zaptec/assets/9033389/aead614e-5f07-4d9b-b0c1-bb8381e9aaea)

**Comment by sveinse** [comment]
I have been wondering about the same. However, the repo doesn't contain the artwork for the logo. @Hellowlol do you know how HA gets the logo?

**Comment by danielkihlgren** [comment]
@sveinse Logo can be found here https://github.com/home-assistant/brands/tree/master/custom_integrations/zaptec

**Comment by sveinse** [comment]
@danielkihlgren or anyone: Any proposals on what should be chosen as the artwork for Zaptec?

**Comment by sveinse** [comment]
Anyone up for the task to contribute new and improved artwork (that works in both light and dark mode) of the Zaptec logo? Here: https://github.com/home-assistant/brands/tree/master/custom_integrations/zaptec

**Comment by c0mplex1** [comment]
Two examples added.
one with a white border around the text
one with grayed out text
Is this a solution?

![icon_gray](https://github.com/user-attachments/assets/f82817e1-62cb-4592-a72d-d4f60bea6789)
![icon_white_border](https://github.com/user-attachments/assets/9e7d3343-ca3c-47d7-b1e6-07263f6458f6)
![logo_gray](https://github.com/user-attachments/assets/3ee5a3a5-e252-4d9d-9105-a087777cef14)
![logo_white_border](https://github.com/user-attachments/assets/cf7c3239-1c83-4974-a146-fbbab467219a)

**Comment by sveinse** [comment]
Game on. PR for changing the logos is underway: https://github.com/home-assistant/brands/pull/6002

I've used more recent logos and with both light and dark variants. Let's cross our finger for swift approval.

**Comment by sveinse** [comment]
This has been approved and merged 💪 , so we can all enjoy the new icons in our HAs already. Closing the issue.
