### ISSUE TITLE
Yaml code does not work on HAOS but works on docker container older version

### ISSUE THREAD

**Issue by badkernel** [custom-components/zaptec#99]
Hello
I have been testing Home assistant in docker for some time now and been using mini graph card to show Zaptec sensors.
I was very happy with the way Zaptec graph looked and installed full version of Home assistant on spare PC and wanted to copy my code to it. Unfortunately code does not work and it does not provide needed information.

Code and result look like this: (removed pasted code and added screenshot)

![image](https://github.com/custom-components/zaptec/assets/51629615/c4d5d9d7-fe4e-4042-802a-1512cafa95d8)

tested also with standard history graph

<img width="491" alt="image" src="https://github.com/custom-components/zaptec/assets/51629615/4009fc0e-59c3-42b6-b36d-7b6972010a57">

HA version in docker
Core 2024.2.5
Frontend 20240207.1

HAOS installed on PC
Core 2024.3.1
Supervisor 2024.03.0
Operating System 12.1
Frontend 20240307.0

Config

![image](https://github.com/custom-components/zaptec/assets/51629615/08d07a86-7521-4fee-997e-71e652c171c9)

**Comment by Hellowlol** [comment]
Can you post a screenshot of the sensor values?

**Comment by badkernel** [comment]
Sensor values ? Please explain @Hellowlol

**Comment by sveinse** [comment]
What is the wanted outcome @badkernel ?

Looking at the sensor Session Total Charge, it increases during charging, but goes to 0 as soon as the charge is over. This the data coming from Zaptec cloud.

<img width="431" alt="image" src="https://github.com/custom-components/zaptec/assets/13770135/14b4f223-9a06-47ac-a99f-97ed7eabf3e5">

**Comment by badkernel** [comment]
Hello @sveinse 
The outcome is to have an overview over change sessions (date and energy usage per session)  as I did with my previous docker container HA.
It looks like this.

<img width="527" alt="image" src="https://github.com/custom-components/zaptec/assets/51629615/46139052-8595-4bfc-8d62-8b962e09b463">


I cannot get this to work on my "full" version of HA installed on spare PC, so I thought to ask here.
You mentioned that data is coming from Zaptec cloud, but I find it strange that it shows fine in previous version of HA and not in the latest one. 

Any help or tips on how to remedy this challenge are appriciated.

**Comment by sveinse** [comment]
These are not problems I've experienced and I'm not sure how we may help unfortunately.

**Comment by sveinse** [comment]
Any updates on this issue? I'd like to close the issue otherwise.
